### ISSUE TITLE
The trait enabled failed to load for NPC - requesting a little more verbosity

### ISSUE THREAD

**Issue by malonnnn** [CitizensDev/Citizens2#1220]
Hello

I get the following error in console when (sometimes) using templates.

[02:48:33 ERROR]: [Citizens] The trait enabled failed to load for NPC ID: 444.

My question is: Can the error be a little more verbose and tell me which trait is failing to load?

Here is NPC ID: 444
```
 '444':
    metadata:
      player-skin-textures: eyJ0aW1lc3RhbXAiOjE0Njk4MTg0OTQ1MzksInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzVkMWE5MGE0ZTgzYWU1ZjAyNWJiNmZmN2Q4NTQxOWQ5MzU2N2M4N2M2NzVkMjgzMDg1OWJiNzQxYzBjOTMzYTkifX19
      player-skin-use-latest: false
      cached-skin-uuid-name: tektronic
      cached-skin-uuid: 87fb3c6c-5ff6-4bf6-b326-992c6137ea12
      player-skin-name: tektronic
      nameplate-visible: false
      player-skin-signature: WvQkfp/wV4xB3GUxakbRkTNN77rUzTRqq6bxV04zl8OSCPkkyeu7350xFRLnbeX0WhvRTy5854wklyMxec/3qKFw2aKC962CG3TB9M+xYTLjqN+dB+UfiOOXrmNgBnFeJBfNZYt6th3H3pJHAfkHOSxzmKOdM8D0ZS0MAefv0Z+5FMqCzsYXXdwi6893lZEv3O2GWXD4Syzn3FViLl0WvAEddrdF/WEnqcLbc0msFkRp+wb0CmhN9MxX/Cy/C04+HuaPg2LCLipkrbVqN5LizyWybWx8FYLXCz9MrRuZ9Gspb1ICzZP8F9qG2TZ3dc5Au55Gox7O2kj0J0ox3XzOfDXf5mBWwU33XJncZMuuRco+sEYwjK0INDAWIbkv2Sesp2ado/oNZltDQsJ8JcpLat9R+Tsf5mYmF3nF0GW4A/5wqBzwwQvH/b+bosXU9ddQepAzAYxhnoX6D1PpPGGTknS8LNW/d4suGrQmoBVs2+ydwPASheiQCCypeovZNBRC1wcImXTtgHsrzfMqHLt1ySmYPF43FYZiECyJF2UrYBJSFsuKsAnzCf2KqwJIhD6M4+Rr84AnmlkENfk+pj8qc10+rGGBWCfRoMs4sez1ml4MPp0SPcpZEygt2w4Zyd2Ooid7FFJ7d8Fqtm2FzUDkylM9VMPtWIkMcWk8VKB+ZOg=
      avoidwater: false
      usedefaultstuckaction: true
      speedmodifier: 1.0
    name: Thanos
    uuid: 9bdab89f-7d4a-43ba-a6c8-e9b913cff97f
    traits:
      gravity:
        enabled: true
      location:
        world: greenfield
        x: '-1726.5'
        y: '70.0'
        z: '132.5'
        yaw: '-90.0'
        pitch: '0.0'
      spawned: true
      type: PLAYER
      owner:
        owner: Tektronic
        uuid: 87fb3c6c-5ff6-4bf6-b326-992c6137ea12
    traitnames: equipment,spawned,owner,location,poses,inventory,gravity,type,mounttrait
    navigator:
      speedmodifier: '1.0'
      avoidwater: false
      usedefaultstuckaction: true
```
