### ISSUE TITLE
Wandering NPC

### ISSUE THREAD

**Issue by KeyTG** [CitizensDev/Citizens2#1331]
Hey there, I'm having issues with NPC wandering?

I am trying to have the npc only wander a small area but am having issues with them wandering off into the wilderness randomly. I have tried using /npc movehere, /npc prange, and the wander waypoint modifiers xrange and yrange to keep him in one area, but none of them have worked. Am I doing something wrong, or is there something else that I can do?

**Comment by Midnight9746** [comment]
Are you using /npc path?

That lets you set waypoints for the npc to walk between.

Example:

A and B, npc will walk back and forth

A, B, and C, npc will walk from a to b to c then back to a.

Watch how far you make the waypoints as the npc might speed up or tp to cover ground, also the surroundings where it might jump up onto blocks and zig zag to the destination.

**Comment by fullwall** [comment]
Latest build adds a tentative way to do this. Basically you can set up regions where the NPC is allowed to wander using the xrange/yrange as a box around each region. I'm not totally happy with how it works but let me know what you think.

**Comment by SlimeDog** [comment]
I am confused. Can you give an example of the commands, please?

**Comment by fullwall** [comment]
/wp provider wander
/npc path

Follow the instructions

**Comment by SlimeDog** [comment]
```
/npc select Killer
/waypoints provider wander
/npc path
```
does not give instructions to set _xrange/yrange_. However, range was set to default:
```
npc:
  '1':
    name: Killer
    uuid: 57523cee-360d-4468-a0fa-46949dfbb3fe
    traits:
      spawned: true
      lookclose:
        enabled: true
        range: '5.0'
        realisticlooking: false
      type: WOLF
      location:
        world: world
        x: '-464.1852'
        y: '69.0'
        z: '-245.076'
        yaw: '271.8398742675781'
        pitch: '0.0'
      waypoints:
        linear:
          points:
            '0':
              location:
                world: world
                x: '-465.5'
                y: '69.0'
                z: '-225.5'
                yaw: '135.0'
                pitch: '0.0'
        provider: wander
        wander:
          xrange: 3
          yrange: 25
      sentinel:
        stats_ticksSpawned: 71420650
        stats_timesSpawned: 2628
        stats_arrowsFired: 0
        stats_potionsThrow: 0
        stats_fireballsFired: 0
        stats_punches: 733
        stats_attackAttempts: 3645
        stats_damageTaken: 8.841066865921022
        stats_damageGiven: 540.9799998402596
        range: 20.0
        damage: 10.0
        armor: -1.0
        health: 20.0
        ranged_chase: false
        close_chase: true
        invincible: false
        fightback: true
        attackRate: 30
        healRate: 30
        guardingUpper: 0
        guardingLower: 0
        needsAmmo: false
        safeShot: true
        respawnTime: 100
        chaseRange: 64.0
        enemyDrops: false
        enemyTargetTime: 0
        stats_snowballsThrown: 0
        stats_eggsThrown: 0
        stats_skullsThrown: 0
        stats_pearlsUsed: 0
        attackRateRanged: 30
        speed: 2.0
        greet_range: 10.0
        autoswitch: false
        accuracy: 0.0
        spawnPoint:
          world: world
          x: '-465.5'
          y: '69.0'
          z: '-225.5'
          yaw: '135.0'
          pitch: '0.0'
        realistic: false
        reach: 3.0
        targets:
          '0': PASSIVE_MOB
          '1': MONSTER
        ignores:
          '0': PLAYER
          '1': OWNER
      wolfmodifiers:
        angry: false
        collarColor: RED
        sitting: false
        tamed: true
      age:
        age: 0
        locked: true
      owner:
        owner: rambeau
        uuid: 3cf9b867-2577-49d1-affb-7ba8196a0d39
    traitnames: type,waypoints,owner,wolfmodifiers,lookclose,mounttrait,location,spawned,sentinel,age,inventory
    navigator:
      stationaryticks: 100
      speedmodifier: '2.0'
      avoidwater: true
      usedefaultstuckaction: true
      pathfindingrange: '100.0'
    metadata:
      protected: false
```
(previous provider was linear). Killer immediately wandered off chasing prey, was soon 100 blocks distant. Obviously, I'm doing something wrong. Help, please.
