### ISSUE TITLE
NPC no talking

### ISSUE THREAD

**Issue by TheMochonful** [CitizensDev/Citizens2#1336]
The NPC do not send messages by chat, I updated the version and still not working, I use the DeluxeChat.

Minecraft Spigot 1.12
Citizens 2.0.22

**Comment by mcmonkey4eva** [comment]
How have you configured the NPCs?

**Comment by xorinzor** [comment]
Having this same issue on spigot 1.12.2 with citizens 2.0.22.

Close talker works fine, but the Random talking doesn't send me anything at all despite being OP and having configured LuckPerms to give me the `citizens.npc.talk` permission

The saves.yml file (snipped some data to keep the project a secret for now): 
```
last-created-npc-id: 0
npc:
  '0':
    name: <snip>
    uuid: <snip>
    traits:
      type: PLAYER
      gravity:
        enabled: false
      spawned: true
      location:
        world: world
        x: '35.124'
        y: '67.0'
        z: '-41.0123'
        yaw: '179.75762939453125'
        pitch: '23.614246368408203'
      text:
        talk-close: true
        random-talker: true
        realistic-looking: false
        range: '7.0'
        talkitem: default
        text:
          '0': '*doing something*'
          '1': I really dont know what to put here
      lookclose:
        enabled: true
        range: '5.0'
        realisticlooking: false
      equipment:
        hand:
          type: GOLDEN_APPLE
          amount: 1
          durability: 1
          mdata: 1
      inventory:
        '0':
          type: GOLDEN_APPLE
          amount: 1
          durability: 1
          mdata: 1
      speech: chat
      owner:
        owner: xorinzor
        uuid: 669176f5-6528-4729-a18c-8c675209e82e
    traitnames: poses,inventory,speech,owner,equipment,gravity,location,text,lookclose,mounttrait,spawned,type
    navigator:
      speedmodifier: '1.0'
      avoidwater: false
      usedefaultstuckaction: true
    metadata:
      player-skin-textures: <snip>
      cached-skin-uuid-name: <snip>
      cached-skin-uuid: <snip>
      player-skin-signature: <snip>
      player-skin-use-latest: false
      player-skin-name: <snip>
```
