### ISSUE TITLE
/npc respawn: doesn't change config values

### ISSUE THREAD

**Issue by Oruss7** [CitizensDev/Citizens2#1365]
Hello,
```
      health:
        animatedeath: false
        respawnondeath: false
        respawndelayinseconds: 60s
        respawnlocation: <npc.flag[respawn_location] || <npc.location>>
```
Still unchanged after settings NPC respawn time to -1...
Must change it from config file ='(

Thanks
