### ISSUE TITLE
GameProfile name and skin name do not match.

### ISSUE THREAD

**Issue by Brokkonaut** [CitizensDev/Citizens2#1410]
Since updating citizens I get the following exception

[05:04:48 WARN]: [Citizens] Task #465 for Citizens v2.0.22-SNAPSHOT (build 1503) generated an exception
java.lang.IllegalArgumentException: GameProfile name (xTICEx) and skin name (jacobus7) do not match.
        at net.citizensnpcs.npc.skin.Skin.setData(Skin.java:268) ~[?:?]
        at net.citizensnpcs.npc.skin.Skin.access$600(Skin.java:32) ~[?:?]
        at net.citizensnpcs.npc.skin.Skin$1.onResult(Skin.java:173) ~[?:?]
        at net.citizensnpcs.npc.profile.ProfileRequest$1.run(ProfileRequest.java:120) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.2.jar:git-Paper-1329]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [patched_1.12.2.jar:git-Paper-1329]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [patched_1.12.2.jar:git-Paper-1329]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1329]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1329]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1329]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by fullwall** [comment]
Can you post the npc savedata for that NPC?

**Comment by Brokkonaut** [comment]
```
  '464':
    name: Jacobus7
    traits:
      spawned: true
      location:
        world: freebuild
        x: '-5565.4988'
        y: '74.5'
        z: '5360.6706'
        yaw: '-146.08541870117188'
        pitch: '0.0'
      inventory: {}
      lookclose:
        enabled: true
        range: '5.0'
        realisticlooking: false
      gravity:
        enabled: false
      type: PLAYER
      owner:
        owner: Brokkonaut
        uuid: 06d29950-2262-474c-acd6-fcab8e632ae1
    traitnames: lookclose,equipment,mounttrait,inventory,spawned,type,owner,location,gravity
    navigator:
      speedmodifier: '1.0'
      avoidwater: false
      usedefaultstuckaction: true
    uuid: eff45e74-ab5f-449d-8371-0fb54e61da57
    metadata:
      cached-skin-uuid: cab10fba-908f-4151-8f9b-b6b0861fcd3e
      cached-skin-uuid-name: jacobus7
      player-skin-textures: eyJ0aW1lc3RhbXAiOjE1MTg3NTM4ODg2NjksInByb2ZpbGVJZCI6ImNhYjEwZmJhOTA4ZjQxNTE4ZjliYjZiMDg2MWZjZDNlIiwicHJvZmlsZU5hbWUiOiJ4VElDRXgiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8v$
      player-skin-signature: l1j2l+DDIgOM5LWDZsqTvlC+yLodHo6VSd7TJYE2BxwWzcl2dqCnSRsosuF7PvFXrIoolMLh1Kz9VORiUqz+2Aur+ZnWT1YnkZuzvIXXURxyac01WnZgOC9FNCqoe3qTUq4+vT0/KVM9QrZXnlqRMPoBN092cwIK9/RsCK/58AyKr85lpHsp2UilK92FhFyze1NM0A1o/INdpWl$
 
```
