### ISSUE TITLE
Sentinels not returning to spawn

### ISSUE THREAD

**Issue by SlimeDog** [CitizensDev/Citizens2#1425]
Spigot 1.12.2
Citizens 2.0.22-b1505
Sentinel 1.4.5

Sentinels are no longer returning to spawn after chasing down an entity kill. No configuration changes, just Citizens update.

Sample configuration:
```
  '11':
    metadata:
      protected: true
    name: Charlie
    uuid: ee27c9ae-d99e-4cbf-a50e-14dfd0656c57
    traits:
      age:
        age: 0
        locked: true
      lookclose:
        enabled: true
        range: '5.0'
        realisticlooking: false
      spawned: true
      waypoints:
        linear: {}
        provider: linear
      wolfmodifiers:
        angry: false
        collarColor: RED
        sitting: false
        tamed: true
      sentinel:
        stats_ticksSpawned: 115528061
        stats_timesSpawned: 237953
        stats_arrowsFired: 0
        stats_potionsThrow: 0
        stats_fireballsFired: 0
        stats_snowballsThrown: 0
        stats_eggsThrown: 0
        stats_skullsThrown: 0
        stats_pearlsUsed: 0
        stats_punches: 4929
        stats_attackAttempts: 35926
        stats_damageTaken: 0.0
        stats_damageGiven: 34901.21953082085
        range: 28.0
        damage: 15.0
        armor: -1.0
        health: 20.0
        ranged_chase: true
        close_chase: true
        invincible: true
        fightback: true
        attackRate: 30
        attackRateRanged: 30
        healRate: 30
        guardingUpper: 0
        guardingLower: 0
        needsAmmo: false
        safeShot: true
        respawnTime: 100
        chaseRange: 64.0
        enemyDrops: false
        enemyTargetTime: 0
        speed: 2.0
        greet_range: 10.0
        autoswitch: false
        accuracy: 0.0
        spawnPoint:
          world: world_blackdog
          x: '14.5'
          y: '71.0'
          z: '11.5'
          yaw: '135.0'
          pitch: '0.0'
        realistic: false
        targets:
          '0': PASSIVE_MOB
          '1': MONSTER
        ignores:
          '0': PLAYER
          '1': OWNER
          '2': CREEPER
      type: WOLF
      location:
        world: world_blackdog
        x: '16.4987'
        y: '71.0'
        z: '11.2849'
        yaw: '-79.83345794677734'
        pitch: '0.0'
      owner:
        owner: HIDDEN
        uuid: HIDDEN
    traitnames: lookclose,mounttrait,age,sentinel,type,constants,inventory,location,owner,spawned,waypoints,wolfmodifiers
    navigator:
      speedmodifier: '2.0'
      avoidwater: false
      usedefaultstuckaction: false
      pathfindingrange: '100.0'
```
