### ISSUE TITLE
Request for NPCs To Load Farms

### ISSUE THREAD

**Issue by MCTyler** [CitizensDev/Citizens2#1444]
Hi, I thought the whole purpose of ``` /npc PlayerList ``` was to use the Npc to keep Chunks loaded even though no one is on the Server. I can confirm this is not working in a Players Cactus Farm.
```
  chunks:
    always-keep-loaded: true
  skins:
    max-retries: -1
    retry-delay: 120
```

Spigot 1.12.2

citizens-2.0.22-SNAPSHOT.jar
