### ISSUE TITLE
Massive amounts of objects being created

### ISSUE THREAD

**Issue by Kneesnap** [CitizensDev/Citizens2#1464]
We have a major memory leak issue in Citizens. With Citizens it brings our TPS down to 10, without Citizens it is a solid 20, and our memory does not fluctuate. From our profiler:

![YourKit Object Allocation](https://i.imgur.com/yJw9bTB.png)

PaperSpigot Version:
This server is running Paper version git-Paper-1169 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
You are 204 version(s) behind

Citizens Version:
Citizens v2.0.22-SNAPSHOT (build 1528)

Server Specs:
32GB RAM
Intel i7 4790k 4Ghz

NPC Count: 443

**Comment by mergu** [comment]
`You are 204 version(s) behind` 🤔
1) Update before posting an issue.
2) Test on Spigot, not Paper.

**Comment by fullwall** [comment]
Thank you for the profiling data. However, you are recording allocations here which is not really a memory leak. Is the problem with garbage collection or memory leaks?

**Comment by Kneesnap** [comment]
Paper is not updated because we wish to support 1.12 and 1.12.X, and ProtocolSupport is not an option. We can test on regular Spigot though. It may not be a leak, but it's a lot of objects getting allocated, and the garbage collector causes a lag-spike when it cleans all of this stuff up. As for which pathfinder we're using, I'm unsure how to check that.

**Comment by fullwall** [comment]
Try latest build. Pathfinder is in config.yml

**Comment by Kneesnap** [comment]
Seems to have fixed the advancement issue, although there are still a lot of objects being allocated by other things.

![Another YourKit Log](https://i.imgur.com/nTJFjq8.png)

As for the pathfinder, I still don't see it in config.yml. I've uploaded it instead.

```yml
# Citizens Configuration

npc:
  chat:
    options:
      bystanders-hear-targeted-chat: false
      max-number-of-targets-to-show: 2
      multiple-targets-format: <target>|, <target>| & <target>| & others
      range: 5
      max-text-range: 500
    format:
      no-targets: '&7<npc>: &f<text>'
      with-target-to-bystanders: '&7<npc>: &f<text>'
      to-target: '&7<npc>: &f<text>'
      with-targets-to-bystanders: '&7<npc>: &f<text>'
  default:
    lookclose: {}
    pathfinding:
      range: 25.0
    talkclose: {}
    look-close:
      enabled: true
      range: 4
    random-talker: false
    realistic-looking: false
    stationary-ticks: -1
    talk-close:
      enabled: false
      range: 3
    text:
      '0': Hello!
  limits:
    default-limit: 20
    max-permission-checks: 10
    max-speed: 100
    max-packet-entries: 15
  chunks:
    always-keep-loaded: false
  selection:
    quick-select: true
    item: '280'
    message: <b>You selected <a><npc><b>!
  player:
    remove-from-list: true
  text:
    max-talk-cooldown: 180
    min-talk-cooldown: 60
    talk-item: '*'
  pathfinding:
    use-new-finder: true
    attack-range: 3.0625
    new-finder-open-doors: false
    default-distance-margin: 2
    update-path-rate: 40
    maximum-new-pathfinder-iterations: 50000
  server-ownership: false
  controllable:
    use-boat-controls: true
  packets:
    update-delay: 40
  skins:
    max-retries: -1
    retry-delay: 120
    rotation-update-degrees: 90.0
    use-latest: true
    view-distance: 100.0
    use-latest-by-default: false
  tablist:
    disable: true
  teleport-delay: -1
  player-scoreboard-teams:
    enable: true
storage:
  database:
    driver: ''
    password: ''
    url: ''
    username: ''
  savetask: {}
  save-task:
    delay: 72000
  file: saves.yml
  type: yaml
general:
  colorscheme: {}
  translation:
    locale: ''
  debug-mode: false
  color-scheme:
    message-highlight: <e>
    message: <a>
  debug-pathfinding: false
  debug-file: ''
  authlib:
    profile-url: https://sessionserver.mojang.com/session/minecraft/profile/
economy:
  npc:
    cost: 100.0
subplugins:
  folder: plugins
advanced:
  check-minecraft-version: false
```
