### ISSUE TITLE
No skin on first encounter

### ISSUE THREAD

**Issue by SlimeDog** [CitizensDev/Citizens2#1541]
```
>version
[06:14:13 INFO]: This server is running CraftBukkit version git-Spigot-0b44fa0-19ff43d (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)
[06:14:13 INFO]: You are 5 version(s) behind
>version Citizens
[06:14:17 INFO]: Citizens version 2.0.23-SNAPSHOT (build 1562)
[06:14:17 INFO]: Website: http://www.citizensnpcs.co
[06:14:17 INFO]: Authors: aPunch and fullwall
```

I have a simple player-skinned NPC for testing. On first encounter after server restart, the NPC is not skinned. If I log out/in, or move out of range then return, the NPC is correctly skinned.

Citizens/saves.yml (this NPC only, player name elided)
```
  '5':
    name: Jack
    uuid: 43cbc0f5-305f-4e8c-8236-05c181923ea8
    traits:
      type: PLAYER
      lookclose:
        enabled: true
        range: '5.0'
        realisticlooking: false
      location:
        world: world
        x: '1996.5'
        y: '88.0'
        z: '-4465.5'
        yaw: '-93.10314178466797'
        pitch: '0.0'
      spawned: true
      waypoints:
        linear:
          points:
            '0':
              location:
                world: world
                x: '1996.5'
                y: '88.0'
                z: '-4465.5'
                yaw: '-69.0'
                pitch: '0.0'
        provider: linear
      age:
        age: 0
        locked: true
      profession: LIBRARIAN
      gravity:
        enabled: false
      equipment: {}
      inventory: {}
      assignment:
        assignment: HELPPLAYGROUND
      triggers:
        enabled:
          CHAT: true
          CLICK: true
          PROXIMITY: true
          DAMAGE: false
        radius:
          PROXIMITY: 4
      owner:
        owner: ELIDED
        uuid: 3cf9b867-2577-49d1-affb-7ba8196a0d39
    traitnames: mounttrait,speech,location,profession,type,triggers,waypoints,assignment,equipment,owner,inventory,constants,anchors,age,gravity,spawned,lookclose
    navigator:
      stationaryticks: 100
      speedmodifier: '2.0'
      avoidwater: true
      usedefaultstuckaction: false
    metadata:
      protected: true
      player-skin-textures: eyJ0aW1lc3RhbXAiOjE1MjA1NTY5MzEyNjEsInByb2ZpbGVJZCI6IjNjZjliODY3MjU3NzQ5ZDFhZmZiN2JhODE5NmEwZDM5IiwicHJvZmlsZU5hbWUiOiJyYW1iZWF1Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9mY2QwYzRlNWMwYjdmOTc3OTIxZWQzYzM0ZjVjYjJiY2U3ZmZmMTE2MzZhZGMyZjI5ZWIxZWE0YjcyMjBjZSIsIm1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9fX19
      cached-skin-uuid-name: ELIDED
      cached-skin-uuid: 3cf9b867-2577-49d1-affb-7ba8196a0d39
      player-skin-signature: Y5urok2wicPLIYUMN0XsgkMhcpJSfO8SCTmyGgEp25jU+LN8soHUxpK0O7JxBSAJzbXJOlTe3ToJjKceCUBZTZ268FW6FjpIw8aCJmHcGURqfx6xWHsEp8gJ5HR34VyLltk9B0OUVXCdTu6nvf2fpO6INlIiikNHeJgIO7UKx2mppLoqspKSU+KhIZY0LtCy8yfcyqzjfTw+Eu5POiEL96UJdruZrex2pOetR5ueptucdfDe1+lgJaqoXa5KlclAt6feKEfEwuwJXkebq8acYYAeasBIpvjTgpR15M1R8g9BPw8777ZQ6281M2HZgVbULk2wCEbsvjReQtFMcEY8Tzef4x1HsJvjrYDLRZcbVVTynObAN26AHoR86WW+zjxvj8Ob5hmNRi+cpVR1nfgiIboIISc8lLCdNriQtZX3XVbhwsh5jst4T6fFIcDW0VD2kCCPvGUWJHN0j6f3HxSkuZ2JUG/ONUwySlWfWtdz6L7wrdl2W8jx2rLnoM1bPeb5wzwIk9+y4pcJoiwdsD2bPK9lSLcR0CvnF1MCc3DuwsvcSreB1D5jnSOT7iizbQLj9hCreC0K1p/zM1Gc9VspadR8AoKbluvDZAxi/sl9ekMWPbkO4dVWA4ljXFqXj/5hyqmNDrAd9JOc8UG24aqgzk1yFnpqZSAjxB6IQ5LMisA=
      player-skin-name: ELIDED
```
Citizens/config.yml (relevant portion)
```
npc:    
...
  chunks:       
    always-keep-loaded: false
  skins:
    max-retries: -1
    retry-delay: 120
    rotation-update-degrees: 90.0
    use-latest: true
    view-distance: 100.0
    use-latest-by-default: false
...
```
