### ISSUE TITLE
Feature Request: Enable AI

### ISSUE THREAD

**Issue by FrankHeijden** [CitizensDev/Citizens2#1618]
An option to let a NPC behave just like a normal spawned entity.

**Comment by mcmonkey4eva** [comment]
You want NPCs to not be NPCs? What?
The main point of an NPC is that it doesn't have default game AI.
If you want normal mobs, spawn in some normal mobs...

**Comment by FrankHeijden** [comment]
I do want them to be NPC's, but want to let them behave like normal mobs and disable certain aspects like player attacking. Also NPC's won't get deleted by chunk unloading.

**Comment by mcmonkey4eva** [comment]
Behaving like normal mobs = not NPCs
Not deleted by chunk unload = a vanilla minecraft option available for entities (remove-when-far-away)
attacking players = basic component of hostile mob AI

**Comment by FrankHeijden** [comment]
I don't want it for every entity, just for the ones I create using citizens. That's why I think it's a great feature, not having attacking phantoms for example, but they cannot be attacked, and do not target a player.

**Comment by mcmonkey4eva** [comment]
The vanilla remove-when-far-away option is per-entity not global.

**Comment by fullwall** [comment]
You mean have control over the vanilla AI aspect of the mobs?

**Comment by FrankHeijden** [comment]
Is this still something? Or not going to implement?

**Comment by mcmonkey4eva** [comment]
This requests seems pretty far out-of-scope for Citizens.

More realistically, you should use traits or scripts that add AI you want to have.

There is a wandering pathfinder available in base Citizens, and a few Denizen scripts floating around that have various forms of NPC wandering logic.
You can enable combat with something like Sentinel.
Other AI elements, find other traits/scripts as relevant...

ALTERNATELY, if you want very vanilla-like AI...
Well, create a vanilla entity. With Denizen you can do something like this:

```yml
safe_phantoms:
    type: world
    debug: false
    events:
        on phantom targets:
        - if <context.entity.has_flag[safe]>:
            - determine cancelled
        on phantom damaged:
        - if <context.entity.has_flag[safe]>:
            - determine cancelled

spawn_safe_phantom:
    type: command
    name: safephantom
    usage: /safephantom
    description: Spawns a safe phantom.
    permission: safe.phantom
    script:
    - spawn phantom[remove_when_far_away=false] save:spawned
    - flag <entry[spawned].spawned_entities.get[1]> safe
```

And then in game use `/safephantom` to spawn one in.

It perfectly fits the early request (a phantom that does not attack and cannot be harmed), and is fairly straightforward and simple to achieve with vanilla mobs.

The script is slightly messier than maybe needed as I made it track a flag on the phantom entity to indicate safe vs. not, and gave a whole dedicated command to spawn them cleanly.
