### ISSUE TITLE
Navigation/Pathing seems to bypass MemoryNPCDataStore

### ISSUE THREAD

**Issue by FerusGrim** [CitizensDev/Citizens2#1789]
The output of command `/version` on my server is: 
```
This server is running Paper version git-Paper-"b72508c2" (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Previous version: git-Paper-"28f5c6a7" (MC: 1.12.2)
```

The output of command `/version citizens` on my server is:
```
Citizens version 2.0.24-SNAPSHOT (build Unknown)
Website: http://www.citizensnpcs.co
Authors: aPunch and fullwall
```

Logs not included; don't contain any pertinent information.

Excerpt from `saves.yml`:
```yaml
  '57':
    name: Guard
    uuid: 5f93bffe-05f9-4b8b-9584-827a3a0047b3
    traits:
      type: PLAYER
      location:
        x: '0.0'
        y: '0.0'
        z: '0.0'
        yaw: '0.0'
        pitch: '0.0'
      spawned: true
      owner:
        owner: server
        uuid: ''
    traitnames: type,spawned,mounttrait,location,owner
    navigator:
      pathfindingrange: '50.0'
      distancemargin: '0.0'
      speedmodifier: '1.0'
      avoidwater: false
      usedefaultstuckaction: true
```

# The Issue

I'm programmatically creating NPCs do perform specific functions. This creation is not meant to be saved to configuration, so I've used a `MemoryNPCDataStore` which is supposed to not save anything:

```java
    private static NPCRegistry getRegistry() {
        final NPCRegistry registry = CitizensAPI.getNamedNPCRegistry(REGISTRY_NAME);
        if (registry == null) {
            return CitizensAPI.createNamedNPCRegistry(REGISTRY_NAME, new MemoryNPCDataStore());
        }
        return registry;
    }
```

Simple enough.

Unfortunately, for whatever reason, some of the entities are being saved, regardless. And it seems as if it's **only** the NPCs which make use of pathing/navigation. None of my other NPCs are being stored to saves.yml.

From what I can gather, the XYZ values are blank, and the information being saved doesn't seem to actually reflect what they're being used for (except the accurate navigational values, such as range and margin), but they're being saved, taking up space, and incrementing the `last-created-npc-id` value.
