### ISSUE TITLE
A door open property for every npc

### ISSUE THREAD

**Issue by CodeDoctorDE** [CitizensDev/Citizens2#1851]
A custom command, eg. /npc door to configure the property for every npc!

Previous property in config.yml:
```
pathfinding:
    default-distance-margin: 2
    default-path-distance-margin: 1
    update-path-rate: 20
    maximum-new-pathfinder-iterations: 50000
   #THIS:
    new-finder-open-doors: true
    attack-range: 3.0625
    use-new-finder: true
```
