### ISSUE TITLE
Shulkers color not working

### ISSUE THREAD

**Issue by alan67160** [CitizensDev/Citizens2#2055]
The output of command `/version` on my server is:
```
[02:10:14] [Render thread/INFO]: [CHAT] This server is running Paper version git-Paper-121 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[02:10:14] [Render thread/INFO]: [CHAT] Checking version, please wait...
[02:10:15] [Render thread/INFO]: [CHAT] Previous version: git-Paper-118 (MC: 1.15.2)
[02:10:15] [Render thread/INFO]: [CHAT] You are running the latest version
```
The output of command `/version citizens` on my server is:
```
[02:16:46] [Render thread/INFO]: [CHAT] Citizens version 2.0.26-SNAPSHOT (build 1832)
[02:16:46] [Render thread/INFO]: [CHAT] Website: http://www.citizensnpcs.co
[02:16:46] [Render thread/INFO]: [CHAT] Author: fullwall
```

`/npc shulker --color lightblue`  command not working

The output of command `/npc shulker --color lightblue` on my server is:
```
[02:18:19] [Render thread/INFO]: [CHAT] NPC1's color set to light blue.
```

The output of command `/npc` on my server is:
```
[02:17:55] [Render thread/INFO]: [CHAT] =====[ NPC1 ]=====
[02:17:55] [Render thread/INFO]: [CHAT]     ID: 51
[02:17:55] [Render thread/INFO]: [CHAT]     Type: SHULKER
[02:17:55] [Render thread/INFO]: [CHAT]     Spawned at -20, 66, 1 in world spawn
[02:17:55] [Render thread/INFO]: [CHAT]     Traits
[02:17:55] [Render thread/INFO]: [CHAT]      - shulkertrait
```

saves.yml:
```
  '51':
    name: §eNPC1
    uuid: 606431c2-4663-45ca-8b9e-b661d18b6003
    traits:
      type: SHULKER
      location:
        world: spawn
        x: '-19.5'
        y: '66.0'
        z: '1.5'
        yaw: '179.7276'
        pitch: '-26.4912'
      lookclose:
        range: '5.0'
        enabled: false
        enableRandomLook: false
        randomLookDelay: 60
        realisticlooking: false
        randomPitchRange:
          '0': -10.0
          '1': 0.0
        randomYawRange:
          '0': 0.0
          '1': 360.0
      spawned: true
      shulkertrait:
        color: LIGHT_BLUE
        peek: 30
      owner:
        owner: server
        uuid: ''
    traitnames: location,owner,shulkertrait,spawned,mounttrait,type,lookclose
    navigator:
      speedmodifier: '1.0'
      avoidwater: false
      usedefaultstuckaction: true
```

config.yml
```
# Citizens Configuration

general:
  authlib:
    profile-url: https://sessionserver.mojang.com/session/minecraft/profile/
  debug-file: ''
  debug-mode: false
  debug-pathfinding: false
  color-scheme:
    message-highlight: <e>
    message: <a>
    message-error: <c>
  translation:
    locale: ''
npc:
  chat:
    options:
      bystanders-hear-targeted-chat: true
      max-number-of-targets-to-show: 2
      multiple-targets-format: <target>|, <target>| & <target>| & others
      range: 5
      max-text-range: 500
    format:
      no-targets: '[<npc>]: <text>'
      with-target-to-bystanders: '[<npc>] -> [<target>]: <text>'
      to-target: '[<npc>] -> You: <text>'
      with-targets-to-bystanders: '[<npc>] -> [<targets>]: <text>'
  pathfinding:
    default-distance-margin: 2
    default-path-distance-margin: 1
    update-path-rate: 20
    maximum-new-pathfinder-iterations: 50000
    new-finder-open-doors: false
    attack-range: 3.0625
    use-new-finder: false
  default:
    look-close:
      enabled: false
      range: 5
      random-look-enabled: false
      random-look-delay: 60
      disable-while-navigating: true
    pathfinding:
      range: 25.0
    random-talker: true
    realistic-looking: false
    stationary-ticks: -1
    talk-close:
      enabled: false
      range: 5
    text:
      '0': Hi, I'm <npc>!
  limits:
    default-limit: 10
    max-permission-checks: 100
    max-packet-entries: 15
    max-speed: 100
  tablist:
    disable: true
  chunks:
    always-keep-loaded: false
  skins:
    max-retries: -1
    retry-delay: 120
    rotation-update-degrees: 90.0
    use-latest-by-default: false
    view-distance: 100.0
  packets:
    update-delay: 30
  selection:
    quick-select: false
    item: stick
    message: <b>You selected <a><npc><b>!
  player:
    remove-from-list: true
  server-ownership: false
  text:
    max-talk-cooldown: 5
    min-talk-cooldown: 10
    talk-item: book
  teleport-delay: -1
  controllable:
    use-boat-controls: true
    max-ground-speed: 0.5
  player-scoreboard-teams:
    enable: true
advanced:
  check-minecraft-version: true
economy:
  npc:
    cost: 100.0
storage:
  save-task:
    delay: 72000
  file: saves.yml
  type: yaml
subplugins:
  folder: plugins
```
