### ISSUE TITLE
[Feature Req] -f argument for /npc tphere 

### ISSUE THREAD

**Issue by LogGits** [CitizensDev/Citizens2#2275]
The argument will perform differently depending on the other arguments used. Whereby -f stands for `-face`. 

**Without cursor arg**
The argument wouldn't change anything.

**With the cursor arg**
It would teleport the npc to the block that the player is looking at and make the npc look at the players eyes (face me).

**Comment by mcmonkey4eva** [comment]
This seems relatively redundant.
Use `/npc pose` to use preset rotations, OR use `/npc look` to make the NPC rotate to face you (and then turn it off after if preferred), OR use `/npc moveto` with the `--yaw` argument.

You could also script the exact sequence of things you want with a simple denizen script, like:
```yml
my_move_command:
  type: command
  name: movenpccursor
  usage: /movenpccursor
  description: Moves your NPC to your cursor, and makes them face you.
  permission: move.npc.cursor
  script:
  - teleport <player.selected_npc> <player.location.cursor_on>
  - look <player.selected_npc> <player.eye_location>
```
