### ISSUE TITLE
npc command issue

### ISSUE THREAD

**Issue by LogGits** [CitizensDev/Citizens2#2312]
`/npc command test <p>`
Using this command will save "test {sendernamehere}" and run "test {originalsendernamehere}".

The output of command `/version` on my server is: **paper 1.16.2 build 175**
The output of command `/version citizens` on my server is: **v2.0.27 build 2105**

**Comment by mcmonkey4eva** [comment]
I'm not sure how you had that happen... it does not happen when I test it, and a lot more people would be complaining if that was an active bug.
Also, you wrote the command wrong at the top of your post (you forgot the `add` argument)

The saves file after running `/npc command add test <p>`:
```yml
    traits:
      commandtrait:
        commands:
          '0':
            command: test <p>
            hand: RIGHT
```

Going to need at a minimum full logs and saves.yml pastebin'd if you think this was anything other than confusion or user error.
