### ISSUE TITLE
"/npc skin --url" does not change skin.

### ISSUE THREAD

**Issue by Shark-vil** [CitizensDev/Citizens2#2375]
### Description
When you change the NPC skin by reference, nothing happens. The skin does not change. If after the creation of the NPC he already has a skin, then it will not change either, not even reset to the default. 

If you save the NPC and look in the config, you can see what the skin was installed. But nothing has changed visually.
Video demonstration - https://youtu.be/XyKos8Uqtfw

### Actions
1. Writing to chat - /npc create <NAME>
2. Writing to chat, looking at the NPC - /npc skin --url https://mc.itpony.ru/skins/knight_1.png
3. Result - skin not change

### Console result
The console does not issue any errors or warnings.

![PuTTY_9z8TrHl58A](https://user-images.githubusercontent.com/13109606/97817269-57ec7900-1cac-11eb-8831-55d6faa36730.png)

### Server info
Core version - paper-251.jar
Minecraft version - 1.16.3
Java version - openjdk version "11.0.8" 2020-07-14
Linux - Debian 10

### Plugins
```
AuthMe-5.6.0-SNAPSHOT.jar
BKCommonLib-1.16.3-v1.jar
ChatControl-Free-5.9.0.jar
Citizens-2.0.27-b2158.jar
Clearlag.jar
craftbook-3.10.2.jar
CustomStructures.jar
DeadChest-4.1.1.jar
Denizen-1.1.7-b5128-DEV.jar
DragonSlayer_0.9.4_Jeppa.jar
dungeonsxl-dist-0.18-SNAPSHOT-1053.jar
EssentialsX-2.18.1.0.jar
EssentialsXChat-2.18.1.0.jar
EssentialsXGeoIP-2.18.1.0.jar
EssentialsXProtect-2.18.1.0.jar
EssentialsXSpawn-2.18.1.0.jar
EssentialsXXMPP-2.18.1.0.jar
FastAsyncWorldEdit-1.16-427.jar
GMusic.jar
GSit.jar
Jobs4.16.2.jar
Kingdoms-1.9.2.jar
LightCleaner-1.16.3-v1.jar
LuckPerms-Bukkit-5.1.93.jar
mcMMO.jar
Multiverse-Core-4.1.0.jar
Multiverse-Portals-4.1.0.jar
MVdWPlaceholderAPI.jar
MythicMobs-4.10.1.jar
OpenInv.jar
PlaceholderAPI-2.10.9.jar
PlayerWarps.jar
PlugMan.jar
ProtocolLib.jar
RandomTeleport-7.9.2.jar
ServerRestorer.jar
SuperVanish-6.2.0.jar
UltimateTimber-2.0.9.jar
Vault.jar
ViaVersion-3.1.1.jar
WorldBorder.jar
WorldEditSUI-1.7.1.jar
worldguard-bukkit-7.0.4-beta1.jar
WorldGuardExtraFlags.jar
```

### NPC info:
```yml
'20':
    metadata:
      cached-skin-uuid-name: d2102143-94cc-4a92-bf33-bbe51b72fb02
    name: Стражник Френк
    uuid: c7610382-6f97-41b5-bc4d-fbc99d8ab638
    traits:
      type: PLAYER
      lookclose:
        range: '5.0'
        enabled: true
        enableRandomLook: false
        randomLookDelay: 60
        realisticlooking: false
        randomPitchRange:
          '0': -10.0
          '1': 0.0
        randomYawRange:
          '0': 0.0
          '1': 360.0
      location:
        bodyYaw: -130.54964
        world: world
        x: '1.4361023791E7'
        y: '90.0'
        z: '-1.04501984709E7'
        yaw: '-130.5496'
        pitch: '0.0'
      spawned: true
      skintrait:
        fetchDefaultSkin: true
        signature: I/YsSgC/LLe0xW3NSOftgpcktwaNDaaTLStCr27U1bSLoivb1kCitONihs+KZMNsrIT+PGrJ0vDVQ1BpeiDPzU0/Gs+dSvL+liXqOY8KfDSDQtUsoaH0HtbK388BH1Yf3y5CUcTrZQ5VNOzea0Q5u3G16IUIjA2/fhRNN5R9H+3cqxM0dl1sk3Qo1bG3LoktJZgyYz/Vs7KFQ6apJu4Wum5fpBcjANyHJzjUXk1usqgb4pStPXOs7oxEbEinB+Ph2lmU55aO366TKbT5NHj2s4gx72d1EyuxJOMZzzZMsX9tSBXmYBksWvvgoT0Oh02QXpk4XTcY55SSeJYvfuE5SAG8wYSFPkBJt7y0GSpBkGziohMbVPLH0sgHoyAjFVbHViEhgrfyR1kcA+a6fBzFcwKIJUULil6xZHVzuvbGibQmfweJvGbKE/+5mTfKS7oV2QgB7EU621ifUNrIOX9F1YFG4iVi/BRBpGkCfUsZ6bojn3ou4m1hw8EK7uTv8IXzDAEFtePxhLY5FJyhgjWm3k1Lfz8dIukVXo4ldXuOBtDwtEL9EP9GbM/ejsxrNEaC4ZNQHufTpALa5qyJszG1JnBfa20G0+YGiyc22PCaSbzvxdh/vfOqKTozD21oxOJSd4h3ljnkW/ehibWJ6swg5HK4A0pitLiyoCyyPF9x2Q0=
        skinName: d2102143-94cc-4a92-bf33-bbe51b72fb02
        textureRaw: ewogICJ0aW1lc3RhbXAiIDogMTYwNDI1MTUyMjU1NiwKICAicHJvZmlsZUlkIiA6ICIyM2YxYTU5ZjQ2OWI0M2RkYmRiNTM3YmZlYzEwNDcxZiIsCiAgInByb2ZpbGVOYW1lIiA6ICIyODA3IiwKICAic2lnbmF0dXJlUmVxdWlyZWQiIDogdHJ1ZSwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2NjYzhlNDIyNDc5YWU1M2Q2ZjBhMGE5YTI4NWUwMjcxMzRhYTY2OWQ1ZWM5OTdlNTgxOGM4MzMxYzVlNzUxNzIiCiAgICB9CiAgfQp9
        updateSkins: false
      skinlayers:
        cape: true
        hat: true
        jacket: true
        left-pants: true
        left-sleeve: true
        right-pants: true
        right-sleeve: true
      owner:
        owner: Shark_vil
        uuid: ff3217a4-9455-3a62-a306-9d1df2fd4a83
    traitnames: scoreboardtrait,spawned,skinlayers,lookclose,owner,inventory,location,type,equipment,skintrait,mounttrait
    navigator:
      speedmodifier: '1.0'
      avoidwater: false
      usedefaultstuckaction: true
```
