### ISSUE TITLE
[Request|Suggestion] Usable Items for NPCs

### ISSUE THREAD

**Issue by Art0sh** [CitizensDev/Citizens2#2625]
This is a suggestion/feature request.

So I wanted to do a npc which holds a spyglass, looking through it.
I was informed that this, at the moment, is not possible, he's just holding it like this.
![image](https://user-images.githubusercontent.com/35751343/127873187-a12bef41-7b77-442f-a8ed-9b08919fcca9.png)
So I want to suggest adding a feature to make a "flag" to the npc thats named "using-item" or something similar, 
making it so it looks like the npc is right-clicking/using the item in his hand like in this image:
![image](https://user-images.githubusercontent.com/35751343/127873080-41639782-d96a-47ca-95e9-16ba9e6dddd8.png)

The output of command `/version` on my server is:
![image](https://user-images.githubusercontent.com/35751343/127872249-53518486-7931-4c01-bb69-1717a47c170a.png)

The output of command `/version citizens` on my server is:
![image](https://user-images.githubusercontent.com/35751343/127872276-93880d82-cadd-4600-b9a1-cea2ec2097b9.png)

**Comment by mcmonkey4eva** [comment]
Until/unless a feature for that is added, you can do with a Denizen script:

```yml

hold_my_item:
    type: assignment
    debug: false
    actions:
        on assignment:
        - trigger name:proximity state:true radius:30
        on move proximity:
        - animate <npc> animation:start_use_mainhand_item
        on remove assignment:
        - animate <npc> animation:stop_use_item

```

Toss that as a `.dsc` in `plugins/Denizen/scripts`, then `/ex reload`, select your NPC, and `/ex assignment set hold_my_item`
