### ISSUE TITLE
CIT-an-id for player's name with skin

### ISSUE THREAD

**Issue by Elikill58** [CitizensDev/Citizens2#2705]
### `/version` output

```txt
Paper 1.8.8-444

This server is running CraftBukkit version git-PaperSpigot-"8230aa68e" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
```

### `/version Citizens` output

```txt
2.0.29-SNAPSHOT (build 2422) download 3 hours ago
```

### Log file

none

### config.yml

https://paste.denizenscript.com/View/90895

### saves.yml

```yml
last-created-npc-id: 9
npc: {}
```

### Description

I have some issue when the player spawn.

This is my code:
```java
NPC npc = REGISTRY.createNPC(EntityType.PLAYER, subName);
npc.spawn(loc, SpawnReason.CREATE);
npc.setAlwaysUseNameHologram(true);
if (skin != null) {
	SkinTrait skinTrait = npc.getOrAddTrait(SkinTrait.class);
	if(skin.getTexture() != null) {
		skinTrait.setSkinName(skin.getName());
		skinTrait.setTexture(skin.getTexture(), skin.getSignature());
	} else {
		skinTrait.setSkinName(skin.getName(), true);
		skinTrait.setFetchDefaultSkin(true);
	}
}
if(itemInHand != null) {
	npc.getOrAddTrait(Equipment.class).set(EquipmentSlot.HAND, itemInHand);
}
npc.getOrAddTrait(HologramTrait.class).setLine(0, displayName);
npc.setName(subName);
```
Sometimes (around 80%), when I join quickly or make them respawn (I completly remove them, then I completly re-add them) :
- Default Steve Skin
- The `CIT-someId` as name (and the other name is showed)

When I don't use skins, I don't have issue.
This is the skin that I used:
```yml
name: "Kaffworld"
texture: "ewogICJ0aW1lc3RhbXAiIDogMTU4Nzc4MjAyNzE2NSwKICAicHJvZmlsZUlkIiA6ICJkZGVkNTZlMWVmOGI0MGZlOGFkMTYyOTIwZjdhZWNkYSIsCiAgInByb2ZpbGVOYW1lIiA6ICJEaXNjb3JkQXBwIiwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2I5ZWNiNmNhY2Q1YWEwMWE3Mzk1ODkwYjYyYmIxYmYxNzg3Y2M0Njk4M2Q4NzY0ZWYxMmRlMDc0Y2JmNzE4NSIKICAgIH0KICB9Cn0="
signature: "CTAAO71Sl66N3TSNnEzWX7cgHbvzRa1qj/qOuhdiTJsG+AZnOw4uIa0HDGg9M9vifGJvcR2T/wUEmzea9gGOVfCSjjSZhuevW3AkZGRCYRXF93qZ88alWZUVs2WwNIVBuEWp+vq5SoboFB0mPWhNxQrLdr8gk7v4tsbgZpN/QRDXAyJgB6zsWqnlTmgQw6Ll4wKkvWRO79gjjTX1nmo6QaFLcox3wonqz01/nViTdZacwGHsEDVS2FEn0SC9Rj1yrLZSbtBSYazy0F9kA2rW1vSheIM/EgqptrpX8YOZSXjEP0JENPZj6IUMLIM+L5VJTCRk77NhufwDbi0S0O2+frTy8asRNq7uhOxAZCB6Hk2rpKLIsvLk08EDYK4HJo2gKmBab6zuLajLgDSvWTG5jS9D5NJEeUp30F8rVQdbBMnxJK5fDc6czm+e8hNaf/jCPxPQpwULNJdnC5IZu9kANfLLPjVMlBCS66TnfifGn9bGe4W7V2Mekgg9DsjdWNig4mb8ucYFT+segH9c9kqBjfeFTZYdBCiwvTpTEyuHCSeeQk2V0Mu6roW0Je8OYWl5Whj0Qi3CcPZ0Sr0HgnRTiQrJLDCdDSzebyWT9mDJ/NS0hTbU2AQduMHIRk3ASSu8npoSwIYD+iiYuNd3fX81ErCvbaT7GIUV7J4ON9E3TdI="
```
I just put the name on [Mineskin](https://mineskin.org/) such as required in doc, then I copy/paste texture/signature. I'm using the name give in the `name` value.

![image](https://user-images.githubusercontent.com/17381066/145910021-5a24c216-66e1-4db7-98db-f250d09685c1.png)
