### ISSUE TITLE
NPC is invisible, can't respawn it

### ISSUE THREAD

**Issue by GriffinCodes** [CitizensDev/Citizens2#2720]
### `/version` output

```txt
git-Parchment-684ee05 1.17.1-R0.1-SNAPSHOT
```

### `/version Citizens` output

```txt
2.0.29-SNAPSHOT (build 2436)
```

### Log file

https://paste.denizenscript.com/View/91593

### config.yml

https://paste.projecteden.gg/raw/citizens2720config

### saves.yml

https://paste.projecteden.gg/raw/citizens2720saves

### Description

I created two NPCs recently and I just noticed that they disappeared. I found their ID in the file and selected them, and did the following:

NPC # 1
- /npc tp - Took me to the correct spot
- /npc despawn - "You despawned \<npc>"
- /npc spawn - Spawned NPC correctly

NPC # 2
- /npc tp - Took me to the correct spot
- /npc despawn - "You despawned \<npc>"
- /npc spawn - Nothing happened, no output in chat
- /npc type player - "\<npc>'s type set to Player"
- /npc tphere - Successfully spawned and teleported NPC

NPC # 2 config (before changing type):
```
  '4535':
    name: §x§a§a§0§0§a§aK§x§b§f§1§5§b§fo§x§d§5§2§b§d§5d§x§e§a§4§0§e§aa§x§f§f§5§5§f§fB§x§f§f§5§5§d§5e§x§f§f§5§5§a§aa§x§f§f§5§5§8§0r
    uuid: ed16a331-d158-4b8f-ae1d-7a7011562511
    traits:
      wolfmodifiers:
        angry: false
        collarColor: RED
        sitting: true
        tamed: false
      lookclose:
        range: '25.0'
        disablewhilenavigating: true
        enabled: true
        enableRandomLook: false
        randomLookDelay: 60
        realisticlooking: false
        randomPitchRange:
          '0': -10.0
          '1': 0.0
        randomYawRange:
          '0': 0.0
          '1': 360.0
      type: WOLF
      spawned: true
      mounttrait:
        mountedon: f6c3c34c-0008-4b10-b21d-7a7d40537219
      hologramtrait:
        direction: BOTTOM_UP
        lineHeight: -1.0
      owner:
        uuid: 86d7e0e2-c95e-4f22-8f99-a6e83b398307
      location:
        bodyYaw: -173.95448
        world: server
        x: '1048.5'
        y: '69.0'
        z: '991.5'
        yaw: '108.907'
        pitch: '-5.6044'
      age:
        age: 0
        locked: true
    traitnames: owner,location,spawned,type,wolfmodifiers,age,hologramtrait,lookclose,mounttrait
    navigator:
      speedmodifier: '1.0'
      avoidwater: false
      usedefaultstuckaction: true
```
