### ISSUE TITLE
Sounds for player type NPCs

### ISSUE THREAD

**Issue by soshimee** [CitizensDev/Citizens2#2820]
### I confirm that I have ...

- [X] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

I need custom death sounds for player type NPCs, but Citizens currently doesn't allow that. It would be nice if Citizens had a way to add sounds for player NPCs.

**Comment by mcmonkey4eva** [comment]
This feature request is a reasonable idea, but so you're aware, you can also handle this yourself using Denizen https://guide.denizenscript.com/

Easy as slapping a script like this in:
```yml
my_npc_sound_thingy:
    type: world
    events:
        on npc_flagged:deathsound dies:
        - playsound <npc.location> <npc.flag[deathsound]>
```
And then selecting your NPC and `/ex flag npc deathsound:ENTITY_WOLF_DEATH` (or any other valid soundname from https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html )
