### ISSUE TITLE
Unable to move NPCs across worlds

### ISSUE THREAD

**Issue by whoshenry** [CitizensDev/Citizens2#403]
I am trying to move an NPC to another world using both the /npc tphere command and the /npc moveto command. In the chat it says the NPC has moved but it actually hasn't, it stays where it was.

No error in the console either and I am using Citizens build 1227 with Spigot 1.8.3.

**Comment by mcmonkey4eva** [comment]
Do you perhaps have an `/npc path` mark defined?

**Comment by whoshenry** [comment]
No this was with a stationary NPC.

**Comment by fullwall** [comment]
Are you using the Multiverse plugin?

**Comment by whoshenry** [comment]
Yes I am.

**Comment by Formula350** [comment]
I, too, am using MultiVerse and *also* am unable to move NPCs from world to world anymore. (Not sure when this started, I feel like in 1.8 but might've been in 1.7.x as well). Tried `/npc tphere` as well as `/npc tptp <npc ID> Formula350`

**Comment by fullwall** [comment]
Do you have any configuration related to multiverse which might block a move across worlds?

**Comment by Formula350** [comment]
@fullwall  Me, personally, I don't *THINK* I do... Here's my MV config, though:
```YAML
multiverse-configuration:
  ==: com.onarandombox.MultiverseCore.MultiverseCoreConfiguration
  enforceaccess: 'false'
  prefixchat: 'false'
  prefixchatformat: '[%world%]%chat%'
  useasyncchat: 'true'
  teleportintercept: 'true'
  firstspawnoverride: 'true'
  displaypermerrors: 'true'
  globaldebug: '0'
  silentstart: 'false'
  messagecooldown: '5000'
  version: '2.9'
  firstspawnworld: world
  teleportcooldown: '1000'
  defaultportalsearch: 'false'
  portalsearchradius: '128'
```
At least, not unless "teleportintercept" is somehow to blame?


...Or did you mean something MV related in the **Citizens** config? In which case... Ooooohh.... It's this, isn't it?
  chunks:
    always-keep-loaded: false
Which due to the chunk the NPC is at, being the chunk I have teleported AWAY from, it is unloaded, thus unloading the NPC?
