### ISSUE TITLE
Error with /template apply

### ISSUE THREAD

**Issue by jewome62** [CitizensDev/Citizens2#854]
Hello,

I have the same problem than : https://github.com/CitizensDev/Citizens2/issues/558

here my templates.yml

I have generated this with template save command

Thanks

**Comment by jewome62** [comment]
```yaml
Guard:
  override: false
  replacements:
    traits.sentinel.stats_damageGiven: 0.0
    traits.sentinel.safeShot: true
    traits.location.pitch: 35.0
    metadata:
      player-skin-textures: eyJ0aW1lc3RhbXAiOjE0Njg3Njc0MDg2NzEsInByb2ZpbGVJZCI6ImE1NmUzM2VhZDZjZTQ2MDRhYWU3OWMwMTkzZmVmMDc1IiwicHJvZmlsZU5hbWUiOiJUcmVlIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8zNjY1NmFkYjE3YWVkMjEzNmZmMjRiNjY5MTI5MjRmNDQyMmI3MmExMjhhY2RmYWVmYWY5MzAzMGFiM2EifX19
      cached-skin-uuid-name: tree
      cached-skin-uuid: a56e33ea-d6ce-4604-aae7-9c0193fef075
      protected: false
      player-skin-signature: F+9k+e7hMHSQ0B9tJ6+f8QXyBJ7SgSbxbpYN/jGoN1nOBbo4hWTT+i3W8RkcaYlEiQ2caL/AbifsFvzx5bzH/aTKH2yXUahQ8WbH4vk6fRrWAj/WY8jwg7zqB2khHQ5vNx7K1BxAwDwy7fK1tF8BhgI/RT2xT6eTlHsJMY1MASYIVdua2+qZv0XgQg50LU5EVkkE7+A5Lt11GURfDwtuuoHXhcbbhoNv/J/IrEnu17o7yk66NANNo3y11Pgza7epwNNn/UfOk38ZTWil3IbhQrr9TQAojHwVqb/z1hxrFcy9xw3Q5ksX1IrkfyxtglgwTNPuUDbZ0xxC1vy9jOGUeW5Du6wxyZFmWIC0UhLq8UVIlfjDUHDIY8KZo35A9krSEdaScf/dvpR6kvC/WXE2jX0PahaNmfhCPyqdjoK5zdar1TZey15Y0eBlnVC0/vNr5sgeNAE5s21sFy4ASuuD+gCGjJOfM9SK2GQSTJtIvb+bW7E4cP4Mej5XgDgerz1TUz1YmU//fO5qICb58W30hsauHNw/+C+YPDdbqWSTq9mUDBHguc+bbJPvdFj2tkaKcxHG3cKRTlkqJ26nQL8WSBi2QtMXh4XlOVGvlfNSOVXcajz+1ToUIapnKY2iYMi4EPAWS/ppTnba9mC4nbh/ucVVtk+FwZW8JULMKYsW8WU=
    traits.equipment.hand: &id001
      type: DIAMOND_SWORD
      amount: 1
      durability: 0
      mdata: 0
    traits.sentinel.ignores.0: OWNER
    traits.sentinel.stats_timesSpawned: 1
    traits.sentinel.guardingLower: 0
    traits.sentinel.ignores: &id002
      '0': OWNER
    traits.sentinel.healRate: 30
    traits.sentinel.respawnTime: 100
    metadata.cached-skin-uuid: a56e33ea-d6ce-4604-aae7-9c0193fef075
    traits.sentinel.targets.0: MONSTERS
    navigator:
      speedmodifier: 1.0
      avoidwater: false
      usedefaultstuckaction: true
    metadata.player-skin-signature: F+9k+e7hMHSQ0B9tJ6+f8QXyBJ7SgSbxbpYN/jGoN1nOBbo4hWTT+i3W8RkcaYlEiQ2caL/AbifsFvzx5bzH/aTKH2yXUahQ8WbH4vk6fRrWAj/WY8jwg7zqB2khHQ5vNx7K1BxAwDwy7fK1tF8BhgI/RT2xT6eTlHsJMY1MASYIVdua2+qZv0XgQg50LU5EVkkE7+A5Lt11GURfDwtuuoHXhcbbhoNv/J/IrEnu17o7yk66NANNo3y11Pgza7epwNNn/UfOk38ZTWil3IbhQrr9TQAojHwVqb/z1hxrFcy9xw3Q5ksX1IrkfyxtglgwTNPuUDbZ0xxC1vy9jOGUeW5Du6wxyZFmWIC0UhLq8UVIlfjDUHDIY8KZo35A9krSEdaScf/dvpR6kvC/WXE2jX0PahaNmfhCPyqdjoK5zdar1TZey15Y0eBlnVC0/vNr5sgeNAE5s21sFy4ASuuD+gCGjJOfM9SK2GQSTJtIvb+bW7E4cP4Mej5XgDgerz1TUz1YmU//fO5qICb58W30hsauHNw/+C+YPDdbqWSTq9mUDBHguc+bbJPvdFj2tkaKcxHG3cKRTlkqJ26nQL8WSBi2QtMXh4XlOVGvlfNSOVXcajz+1ToUIapnKY2iYMi4EPAWS/ppTnba9mC4nbh/ucVVtk+FwZW8JULMKYsW8WU=
    navigator.speedmodifier: 1.0
    uuid: 4594017d-e266-4696-a33b-d762abe41cf3
    traits.equipment.hand.amount: 1
    navigator.avoidwater: false
    traits.sentinel.attackRate: 30
    traits.sentinel.enemyTargetTime: 0
    traits.location.world: Heart-Craft
    traits.sentinel.stats_fireballsFired: 0
    metadata.protected: false
    traits.sentinel.stats_punches: 0
    traits.sentinel.stats_damageTaken: 0.0
    metadata.player-skin-textures: eyJ0aW1lc3RhbXAiOjE0Njg3Njc0MDg2NzEsInByb2ZpbGVJZCI6ImE1NmUzM2VhZDZjZTQ2MDRhYWU3OWMwMTkzZmVmMDc1IiwicHJvZmlsZU5hbWUiOiJUcmVlIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8zNjY1NmFkYjE3YWVkMjEzNmZmMjRiNjY5MTI5MjRmNDQyMmI3MmExMjhhY2RmYWVmYWY5MzAzMGFiM2EifX19
    traits.spawned: true
    traits.sentinel.needsAmmo: false
    traits.sentinel.guardingUpper: 0
    traits.sentinel.stats_ticksSpawned: 1901
    traits.inventory.0.mdata: 0
    traits.equipment.hand.type: DIAMOND_SWORD
    traits.owner: &id005
      owner: jewome62
      uuid: 7c7a0cb7-9b76-4e7e-a433-dd0b5caa1ead
    traits.owner.uuid: 7c7a0cb7-9b76-4e7e-a433-dd0b5caa1ead
    traits.equipment: &id004
      hand: *id001
    traits.sentinel: &id006
      stats_ticksSpawned: 1901
      stats_timesSpawned: 1
      stats_arrowsFired: 0
      stats_potionsThrow: 0
      stats_fireballsFired: 0
      stats_punches: 0
      stats_attackAttempts: 0
      stats_damageTaken: 0.0
      stats_damageGiven: 0.0
      targets: &id008
        '0': MONSTERS
      ignores: *id002
      range: 20.0
      damage: -1.0
      armor: -1.0
      health: 20.0
      ranged_chase: false
      close_chase: true
      invincible: false
      fightback: true
      attackRate: 30
      healRate: 30
      guardingUpper: 0
      guardingLower: 0
      needsAmmo: false
      safeShot: true
      respawnTime: 100
      chaseRange: 100.0
      enemyDrops: false
      enemyTargetTime: 0
    traits.sentinel.range: 20.0
    traits.sentinel.chaseRange: 100.0
    traits.location: &id007
      world: Heart-Craft
      x: -357.788
      y: 65.5
      z: -1865.8442
      yaw: 57.0
      pitch: 35.0
    traits.sentinel.ranged_chase: false
    traits.location.yaw: 57.0
    name: Tree
    traits.sentinel.stats_potionsThrow: 0
    traits.inventory: &id003
      '0': &id009
        type: DIAMOND_SWORD
        amount: 1
        durability: 0
        mdata: 0
    traits.owner.owner: jewome62
    traits:
      inventory: *id003
      equipment: *id004
      owner: *id005
      sentinel: *id006
      location: *id007
      spawned: true
    traits.sentinel.targets: *id008
    traits.sentinel.fightback: true
    traits.inventory.0.amount: 1
    traits.equipment.hand.durability: 0
    traits.equipment.hand.mdata: 0
    traits.sentinel.health: 20.0
    navigator.usedefaultstuckaction: true
    traits.sentinel.enemyDrops: false
    traits.inventory.0.type: DIAMOND_SWORD
    traitnames: inventory,type,equipment,owner,sentinel,location,spawned
    traits.location.z: -1865.8442
    traits.inventory.0.durability: 0
    traits.location.y: 65.5
    traits.sentinel.armor: -1.0
    traits.location.x: -357.788
    traits.sentinel.stats_arrowsFired: 0
    metadata.cached-skin-uuid-name: tree
    traits.inventory.0: *id009
    traits.sentinel.stats_attackAttempts: 0
    traits.sentinel.close_chase: true
    traits.sentinel.invincible: false
    traits.sentinel.damage: -1.0
test:
  override: false
  replacements:
    traits.sentinel.stats_damageGiven: 0.0
    traits.sentinel.safeShot: true
    traits.location.pitch: 35.21242904663086
    metadata:
      player-skin-textures: eyJ0aW1lc3RhbXAiOjE0Njg3Njc4NzQ0MTQsInByb2ZpbGVJZCI6ImE1NmUzM2VhZDZjZTQ2MDRhYWU3OWMwMTkzZmVmMDc1IiwicHJvZmlsZU5hbWUiOiJUcmVlIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8zNjY1NmFkYjE3YWVkMjEzNmZmMjRiNjY5MTI5MjRmNDQyMmI3MmExMjhhY2RmYWVmYWY5MzAzMGFiM2EifX19
      cached-skin-uuid-name: tree
      cached-skin-uuid: a56e33ea-d6ce-4604-aae7-9c0193fef075
      protected: false
      player-skin-signature: UQ2pjz8f8X/QO5DejkGOBQtEpD8F1LiLBn3YLSslhRFkEok2l0VGQsKksY6xTx4ZAMS/eKCKAOlOQrECu9K8btw/ZVC4eObiwqgCgiLcosXfHZLafYsnc5JdwBKEfkpKA1VRadxy8ZV+PiGZf0xgP6Bf5bpQ6ipY7Qw/VXLD6Sjv6/A/AYu89T8gP15uuf02ClSBtgxyCQWUc5k/pfgdmhARiw7yY6bsfLGfvP+NRRnUT4mANPmEi9HVIylbbs/GHZCrKO9zs9DEGr7gTxDFNjjX/iyiLgzERSCpCSIgU1ugjxet3bpWDaYrxJkZ1AgLhYb3kKpRZd/IkzqYJqNsDnOglB6M/EuVCjAiQ/TcsHogbLBx6tz7Hnu+OT5V8r+jryx0/kKow48QW9j/6rgxAyZDIlkPByXI+5haAOEvtPP/m7pE5+/7jo1N9/TX/keD4jMgltcyPN9kLQSOmQTSCumT4z3yGql/r3J2pBwrFcmDwBoNfLrGbJKR5h8eDH2FgH9DDfqAd1xMGt66yq8vOWTNS9wXPGZ700ZamBUlFJj4mlL2wCFdRDFIgxt1dhSFvxotJm+GnPziln//KjtOaXc1WAtpzuJgmHDe9hEouEyVZBGrDwobKCjCFAr1tUUkAFwlEYMSwdYGvDphZnCrClIYa6zuEYuwDB9DRc8+45k=
    traits.equipment.hand: &id010
      type: DIAMOND_SWORD
      amount: 1
      durability: 0
      mdata: 0
    traits.sentinel.ignores.0: OWNER
    traits.sentinel.stats_timesSpawned: 3
    traits.sentinel.guardingLower: 0
    traits.sentinel.ignores: &id011
      '0': OWNER
    traits.sentinel.healRate: 30
    traits.sentinel.respawnTime: 100
    metadata.cached-skin-uuid: a56e33ea-d6ce-4604-aae7-9c0193fef075
    traits.sentinel.targets.0: MONSTERS
    navigator:
      speedmodifier: 1.0
      avoidwater: false
      usedefaultstuckaction: true
    metadata.player-skin-signature: UQ2pjz8f8X/QO5DejkGOBQtEpD8F1LiLBn3YLSslhRFkEok2l0VGQsKksY6xTx4ZAMS/eKCKAOlOQrECu9K8btw/ZVC4eObiwqgCgiLcosXfHZLafYsnc5JdwBKEfkpKA1VRadxy8ZV+PiGZf0xgP6Bf5bpQ6ipY7Qw/VXLD6Sjv6/A/AYu89T8gP15uuf02ClSBtgxyCQWUc5k/pfgdmhARiw7yY6bsfLGfvP+NRRnUT4mANPmEi9HVIylbbs/GHZCrKO9zs9DEGr7gTxDFNjjX/iyiLgzERSCpCSIgU1ugjxet3bpWDaYrxJkZ1AgLhYb3kKpRZd/IkzqYJqNsDnOglB6M/EuVCjAiQ/TcsHogbLBx6tz7Hnu+OT5V8r+jryx0/kKow48QW9j/6rgxAyZDIlkPByXI+5haAOEvtPP/m7pE5+/7jo1N9/TX/keD4jMgltcyPN9kLQSOmQTSCumT4z3yGql/r3J2pBwrFcmDwBoNfLrGbJKR5h8eDH2FgH9DDfqAd1xMGt66yq8vOWTNS9wXPGZ700ZamBUlFJj4mlL2wCFdRDFIgxt1dhSFvxotJm+GnPziln//KjtOaXc1WAtpzuJgmHDe9hEouEyVZBGrDwobKCjCFAr1tUUkAFwlEYMSwdYGvDphZnCrClIYa6zuEYuwDB9DRc8+45k=
    navigator.speedmodifier: 1.0
    uuid: 4594017d-e266-4696-a33b-d762abe41cf3
    traits.equipment.hand.amount: 1
    navigator.avoidwater: false
    traits.sentinel.attackRate: 30
    traits.sentinel.enemyTargetTime: 0
    traits.location.world: Heart-Craft
    traits.sentinel.stats_fireballsFired: 0
    metadata.protected: false
    traits.sentinel.stats_punches: 0
    traits.sentinel.stats_damageTaken: 0.0
    metadata.player-skin-textures: eyJ0aW1lc3RhbXAiOjE0Njg3Njc4NzQ0MTQsInByb2ZpbGVJZCI6ImE1NmUzM2VhZDZjZTQ2MDRhYWU3OWMwMTkzZmVmMDc1IiwicHJvZmlsZU5hbWUiOiJUcmVlIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8zNjY1NmFkYjE3YWVkMjEzNmZmMjRiNjY5MTI5MjRmNDQyMmI3MmExMjhhY2RmYWVmYWY5MzAzMGFiM2EifX19
    traits.spawned: true
    traits.sentinel.needsAmmo: false
    traits.sentinel.guardingUpper: 0
    traits.sentinel.stats_ticksSpawned: 14281
    traits.inventory.0.mdata: 0
    traits.equipment.hand.type: DIAMOND_SWORD
    traits.owner: &id014
      owner: jewome62
      uuid: 7c7a0cb7-9b76-4e7e-a433-dd0b5caa1ead
    traits.owner.uuid: 7c7a0cb7-9b76-4e7e-a433-dd0b5caa1ead
    traits.equipment: &id013
      hand: *id010
    traits.sentinel: &id015
      stats_ticksSpawned: 14281
      stats_timesSpawned: 3
      stats_arrowsFired: 0
      stats_potionsThrow: 0
      stats_fireballsFired: 0
      stats_punches: 0
      stats_attackAttempts: 0
      stats_damageTaken: 0.0
      stats_damageGiven: 0.0
      targets: &id017
        '0': MONSTERS
      ignores: *id011
      range: 20.0
      damage: -1.0
      armor: -1.0
      health: 20.0
      ranged_chase: false
      close_chase: true
      invincible: false
      fightback: true
      attackRate: 30
      healRate: 30
      guardingUpper: 0
      guardingLower: 0
      needsAmmo: false
      safeShot: true
      respawnTime: 100
      chaseRange: 100.0
      enemyDrops: false
      enemyTargetTime: 0
    traits.sentinel.range: 20.0
    traits.sentinel.chaseRange: 100.0
    traits.location: &id016
      world: Heart-Craft
      x: -357.563
      y: 65.5
      z: -1866.0354
      yaw: 57.65789031982422
      pitch: 35.21242904663086
    traits.sentinel.ranged_chase: false
    traits.location.yaw: 57.65789031982422
    name: Tree
    traits.sentinel.stats_potionsThrow: 0
    traits.inventory: &id012
      '0': &id018
        type: DIAMOND_SWORD
        amount: 1
        durability: 0
        mdata: 0
    traits.owner.owner: jewome62
    traits:
      inventory: *id012
      equipment: *id013
      owner: *id014
      sentinel: *id015
      location: *id016
      spawned: true
    traits.sentinel.targets: *id017
    traits.sentinel.fightback: true
    traits.inventory.0.amount: 1
    traits.equipment.hand.durability: 0
    traits.equipment.hand.mdata: 0
    traits.sentinel.health: 20.0
    navigator.usedefaultstuckaction: true
    traits.sentinel.enemyDrops: false
    traits.inventory.0.type: DIAMOND_SWORD
    traitnames: inventory,type,equipment,owner,sentinel,location,spawned
    traits.location.z: -1866.0354
    traits.inventory.0.durability: 0
    traits.location.y: 65.5
    traits.sentinel.armor: -1.0
    traits.location.x: -357.563
    traits.sentinel.stats_arrowsFired: 0
    metadata.cached-skin-uuid-name: tree
    traits.inventory.0: *id018
    traits.sentinel.stats_attackAttempts: 0
    traits.sentinel.close_chase: true
    traits.sentinel.invincible: false
    traits.sentinel.damage: -1.0

```
