### ISSUE TITLE
WIKI? Explanations?

### ISSUE THREAD

**Issue by bloggy** [CitizensDev/Citizens2#953]
There are lots of settings in the config which are not explained anywhere. Or is there a wiki covering these informations?

Example:

```
  skins:
    max-retries: -1
    retry-delay: 120
    use-latest: true
    view-distance: 40.0
    rotation-update-degrees: 90.0
```

What is view distance? etc.
Are there any settings I could tweak regarding performance?
