### ISSUE TITLE
Chicken NPC causing Exception

### ISSUE THREAD

**Issue by crysis992** [CitizensDev/Citizens2#986]
When starting the server, Citizens does not load the NPCs with the EntityType chicken. It is throwing an error instead: http://pastebin.com/QZwcaBDT

Tested with build 1430 - 1436

saves.yml entry of the affected NPC.

```
  '10':
    name: ยง4Snack
    uuid: 88a312ff-04c5-416f-8bac-2b81c5dca0ec
    traits:
      spawned: true
      type: CHICKEN
      age:
        age: 0
        locked: true
      location:
        world: world
        x: '31.4707'
        y: '63.3125'
        z: '15.5068'
        yaw: '-226.78228759765625'
        pitch: '0.0'
      owner:
        owner: _EFFIX_
        uuid: a1bb7b8b-a460-4e3b-8797-d66490dedfdc
    traitnames: spawned,type,age,location,owner
    navigator:
      speedmodifier: '1.0'
      avoidwater: false
      usedefaultstuckaction: true
```

Using the latest version of PaperSpigot

>version
`[15:11:38 INFO]: This server is running Paper version git-Paper-933 (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT)`
